import{useState}from"react";import{LayoutDashboard,Palette,WandSparkles,Activity,Settings,Search,Bot,ChevronRight,ArrowUpRight,Sparkles,Gamepad2,Users,Mic2,ShieldCheck,Languages,Menu,X,Server,Zap,CheckCircle2}from"lucide-react";

const templates=[
{name:"Gaming Community",category:"Gaming",desc:"Competitive community layout with social, voice and moderation spaces.",accent:"#d4af37",icon:Gamepad2,channels:24,roles:12},
{name:"Streamer Hub",category:"Streaming",desc:"A creator-focused server for followers, announcements and live interaction.",accent:"#8b5cf6",icon:Mic2,channels:21,roles:10},
{name:"FiveM Roleplay",category:"Roleplay",desc:"Structured RP server with staff, departments and player support.",accent:"#22c55e",icon:ShieldCheck,channels:32,roles:18},
{name:"Anime Community",category:"Anime",desc:"A polished fandom space for discussion, media and events.",accent:"#ec4899",icon:Sparkles,channels:22,roles:11},
{name:"Tech & AI Hub",category:"Tech",desc:"A clean workspace for developers, AI builders and projects.",accent:"#38bdf8",icon:Zap,channels:26,roles:14},
{name:"Study Campus",category:"Study",desc:"Study rooms, resources, accountability and voice spaces.",accent:"#f59e0b",icon:Users,channels:20,roles:9}
];

function App(){
 const[page,setPage]=useState("Dashboard");const[mobile,setMobile]=useState(false);const[language,setLanguage]=useState("English");const[selected,setSelected]=useState(null);
 const nav=[["Dashboard",LayoutDashboard],["Templates",Palette],["Builder",WandSparkles],["Server",Server],["Activity",Activity],["Settings",Settings]];
 const invite=()=>window.open("https://discord.com/oauth2/authorize","_blank");
 return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brand-mark">N</div><div><strong>LiveNest</strong><span>Discord Setup</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="workspace"><div className="workspace-icon"><Bot/></div><div><small>WORKSPACE</small><b>LiveNest Community</b></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={page===name?"nav active":"nav"} onClick={()=>{setPage(name);setMobile(false)}}><Icon/><span>{name}</span></button>)}</nav><div className="side-bottom"><div className="free"><Sparkles/><b>Free forever</b><p>No subscriptions. No paywalls.</p></div><div className="user"><div className="avatar">SN</div><div><b>Siik Notic</b><span>Owner</span></div></div></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<main><header><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">LiveNest <ChevronRight/> <b>{page}</b></div><div className="actions"><button className="lang" onClick={()=>setLanguage(language==="English"?"Español":"English")}><Languages/> {language}</button><button className="invite" onClick={invite}><Bot/> Invite Bot</button></div></header><div className="content">{page==="Dashboard"&&<Dashboard go={setPage} select={setSelected}/>} {page==="Templates"&&<Templates select={setSelected} selected={selected}/>} {page==="Builder"&&<Builder selected={selected}/>} {page==="Server"&&<ServerPage invite={invite}/>} {page==="Activity"&&<Empty title="Everything LiveNest changes." icon={<Activity/>}/>} {page==="Settings"&&<SettingsPage language={language}/>}</div></main></div>
}

function Dashboard({go,select}){return <section><div className="hero"><div><label>● FREE DISCORD SERVER BUILDER</label><h1>Build your Discord.<br/><em>Your way.</em></h1><p>Choose a premium template, customize it, and install it safely in minutes. No subscriptions. No paywalls.</p><div className="hero-actions"><button className="primary" onClick={()=>go("Templates")}>Explore templates <ArrowUpRight/></button><button className="secondary"><Bot/> Invite Bot</button></div></div><div className="hero-logo"><div>N</div><span>100%<small>FREE</small></span></div></div><Head title="Your workspace" action="View server" onClick={()=>go("Server")}/><div className="stats"><Stat title="Server status" value="Not connected" icon={<Server/>}/><Stat title="Templates" value="46+" icon={<Palette/>}/><Stat title="Languages" value="3 modes" icon={<Languages/>}/><Stat title="Price" value="Free" icon={<Sparkles/>}/></div><Head title="Featured templates" action="View all" onClick={()=>go("Templates")}/><div className="grid">{templates.slice(0,3).map(t=><Card key={t.name} t={t} onClick={()=>{select(t);go("Builder")}}/>)}</div></section>}

function Head({title,action,onClick}){return <div className="section-head"><div><label>OVERVIEW</label><h2>{title}</h2></div><button className="ghost" onClick={onClick}>{action}<ChevronRight/></button></div>}
function Stat({title,value,icon}){return <div className="stat"><div>{icon}</div><span>{title}</span><b>{value}</b></div>}

function Templates({select,selected}){const[q,setQ]=useState("");const list=templates.filter(t=>(t.name+t.category).toLowerCase().includes(q.toLowerCase()));return <section><div className="page-title"><div><label>TEMPLATE LIBRARY</label><h1>Start with a great server.</h1><p>Professional Discord structures, ready to customize.</p></div><div className="search"><Search/><input placeholder="Search templates..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="filters"><button>All</button><button>Gaming</button><button>Roleplay</button><button>Streaming</button><button>Anime</button><button>Tech</button><button>Study</button></div><div className="grid">{list.map(t=><Card key={t.name} t={t} selected={selected&&selected.name===t.name} onClick={()=>select(t)}/>)}</div></section>}

function Card({t,onClick,selected}){const Icon=t.icon;return <button className={selected?"card selected":"card"} onClick={onClick} style={{"--accent":t.accent}}><div className="art"><Icon/><span>{t.category}</span></div><div className="card-body"><small>{t.category}</small><h3>{t.name}</h3><p>{t.desc}</p><footer><span>{t.channels} channels</span><span>{t.roles} roles</span><b>Preview <ArrowUpRight/></b></footer></div></button>}

function Builder({selected}){const[step,setStep]=useState(1);const[lang,setLang]=useState("both");return <section><div className="page-title"><div><label>SERVER BUILDER</label><h1>Build it before you install it.</h1><p>Review every change before LiveNest touches Discord.</p></div></div><div className="steps">{["Template","Language","Customize","Review"].map((x,i)=><button key={x} className={step===i+1?"step active":"step"} onClick={()=>setStep(i+1)}><b>{i+1}</b>{x}</button>)}</div><div className="builder">{step===1&&<><Panel icon={<Palette/>} title={selected?selected.name:"Choose a template"} text={selected?selected.desc:"Select a template from the library to begin."}/><div className="selected-template">{selected?"✓ "+selected.name:"No template selected"}</div><button className="primary" onClick={()=>setStep(2)}>Continue <ChevronRight/></button></>}{step===2&&<><Panel icon={<Languages/>} title="How should your server speak?" text="Choose the language structure for the entire installation."/><div className="language-grid">{[["en","🇺🇸 English","Everything in English."],["es","🇪🇸 Español","Todo en español."],["both","🌎 English + Español","A truly bilingual server."]].map(x=><button key={x[0]} className={lang===x[0]?"language-option active":"language-option"} onClick={()=>setLang(x[0])}><strong>{x[1]}</strong><span>{x[2]}</span><CheckCircle2/></button>)}</div><button className="primary" onClick={()=>setStep(3)}>Continue <ChevronRight/></button></>}{step===3&&<><Panel icon={<WandSparkles/>} title="Customize your setup" text="Choose the features you want included."/><div className="options">{["Welcome & onboarding","Moderation structure","Support / tickets","Reaction roles","Community voice rooms"].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i<3}/>{x}<small>{i<3?"Recommended":"Optional"}</small></label>)}</div><button className="primary" onClick={()=>setStep(4)}>Review changes <ChevronRight/></button></>}{step===4&&<><Panel icon={<CheckCircle2/>} title="Ready to install" text="Nothing changes in Discord until you confirm."/><div className="changes"><div><small>CREATE</small><b>+ {selected?selected.channels:0} channels</b><b>+ {selected?selected.roles:0} roles</b></div><div><small>LANGUAGE</small><b>{lang==="both"?"English + Español":lang==="en"?"English":"Español"}</b></div><div><small>PRICE</small><b>Free forever</b></div></div><button className="primary wide"><Zap/> Install to Discord</button></>}</div></section>}

function Panel({icon,title,text}){return <div className="panel-title">{icon}<div><h2>{title}</h2><p>{text}</p></div></div>}
function ServerPage({invite}){return <section><div className="page-title"><div><label>SERVER</label><h1>Connect your Discord.</h1><p>Invite the LiveNest bot and manage your server from one place.</p></div><button className="primary" onClick={invite}><Bot/> Invite Bot</button></div><Empty title="No server connected" icon={<Server/>}/></section>}
function Empty({title,icon}){return <div className="empty">{icon}<h2>{title}</h2><p>Install your first template and every action will appear here.</p></div>}
function SettingsPage({language}){return <section><div className="page-title"><div><label>SETTINGS</label><h1>Your preferences.</h1><p>Control the LiveNest Setup experience.</p></div></div><div className="settings"><div><Languages/><b>Application language</b><span>{language}</span><CheckCircle2/></div><div><ShieldCheck/><b>Safe installation</b><span>Review changes before applying them.</span><CheckCircle2/></div><div><Sparkles/><b>Pricing</b><span>Completely free.</span><CheckCircle2/></div></div></section>}

export default App;