/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicDiscordLoginRouteImport } from './routes/api/public/discord/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordLoginRoute = ApiPublicDiscordLoginRouteImport.update({
  id: '/api/public/discord/login',
  path: '/api/public/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  id:
    | '__root__'
    | '/'
    | '/setup'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupRoute: typeof SetupRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordLoginRoute: typeof ApiPublicDiscordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/login': {
      id: '/api/public/discord/login'
      path: '/api/public/discord/login'
      fullPath: '/api/public/discord/login'
      preLoaderRoute: typeof ApiPublicDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupRoute: SetupRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordLoginRoute: ApiPublicDiscordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
